In [3]:
import nfl_data_py as nfl

pbp = nfl.import_pbp_data([2020, 2021, 2022, 2023, 2024, 2025])
rosters = nfl.import_weekly_rosters([2020, 2021, 2022, 2023, 2024, 2025])

2020 done.
2021 done.
2022 done.
2023 done.
2024 done.
2025 done.
Downcasting floats.

In [4]:
rosters = nfl.import_weekly_rosters([2020, 2021, 2022, 2023, 2024, 2025])

In [5]:
rosters.status.unique()

array(['UFA', 'ACT', 'RES', 'INA', 'DEV', 'EXE', 'CUT', 'NWT', 'RSR',
       'TRC', 'TRD', 'SUS', 'PUP', 'RFA', 'TRT', 'RSN', 'RET', 'E01',
       'E14'], dtype=object)

In [6]:
rosters_clean = rosters[rosters.status.isin(['ACT', 'RES', 'INA', 'SUS', 'PUP'])]

In [7]:
import sqlite3
conn = sqlite3.connect("nfl.db")

In [8]:
pbp.to_sql("play_by_play", conn, if_exists="replace", index=False)

294989

In [9]:
rosters_clean.to_sql("weekly_rosters", conn, if_exists="replace", index=False)

216720

In [10]:
import pandas as pd

In [11]:
for x in pbp.columns:
    print(x)

play_id
game_id
old_game_id_x
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe
nflverse_game_id
old_game_id_y
possession_team
offense_formation
offense_personnel
defenders_in_box
defense_personnel
number_of_pass_rushers
players_on_play
offense_players
defense_players
n_offense
n_defense
ngs_air_yards
time_to_throw
was_pressure
route
defense_man_zone_type
defense_coverage_type
offense_names
defense_names
offense_positions
defense_positions
offense_numbers
defense_numbers

In [12]:
pd.read_sql("SELECT passer_player_id, passer_player_name, passing_yards FROM play_by_play WHERE season = 2024 AND passer_player_id IS NOT NULL LIMIT 5", conn)

  passer_player_id passer_player_name  passing_yards
0       00-0035228           K.Murray           22.0
1       00-0035228           K.Murray            9.0
2       00-0035228           K.Murray            8.0
3       00-0035228           K.Murray            NaN
4       00-0035228           K.Murray            NaN

In [15]:
pd.read_sql("SELECT * FROM weekly_rosters WHERE season = 2024", conn)

,season,team,position,depth_chart_position,jersey_number,status,player_name,first_name,last_name,birth_date,...,status_description_abbr,football_name,esb_id,gsis_it_id,smart_id,entry_year,rookie_year,draft_club,draft_number,age
0,2024,NYJ,QB,QB,8.0,ACT,Aaron Rodgers,Aaron,Rodgers,1983-12-02 00:00:00,...,A01,Aaron,ROD339293,29851,3200524f-4433-9293-a3cf-ad7758d03003,2005.0,2005.0,GB,24.0,40.914
1,2024,NYJ,QB,QB,8.0,ACT,Aaron Rodgers,Aaron,Rodgers,1983-12-02 00:00:00,...,A01,Aaron,ROD339293,29851,3200524f-4433-9293-a3cf-ad7758d03003,2005.0,2005.0,GB,24.0,40.903
2,2024,NYJ,QB,QB,8.0,ACT,Aaron Rodgers,Aaron,Rodgers,1983-12-02 00:00:00,...,A01,Aaron,ROD339293,29851,3200524f-4433-9293-a3cf-ad7758d03003,2005.0,2005.0,GB,24.0,40.884
3,2024,NYJ,QB,QB,8.0,ACT,Aaron Rodgers,Aaron,Rodgers,1983-12-02 00:00:00,...,A01,Aaron,ROD339293,29851,3200524f-4433-9293-a3cf-ad7758d03003,2005.0,2005.0,GB,24.0,40.827
4,2024,NYJ,QB,QB,8.0,ACT,Aaron Rodgers,Aaron,Rodgers,1983-12-02 00:00:00,...,A01,Aaron,ROD339293,29851,3200524f-4433-9293-a3cf-ad7758d03003,2005.0,2005.0,GB,24.0,40.999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36401,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13 00:00:00,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,25.027
36402,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13 00:00:00,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,25.095
36403,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13 00:00:00,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,25.295
36404,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13 00:00:00,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,25.046
36405,2024,NO,DL,DT,76.0,RES,Camron Peterson,Camron,Peterson,1999-09-13 00:00:00,...,R01,Camron,PAT382575,58061,32005041-5438-2575-6a39-c3744d58b516,2024.0,2024.0,None,NaN,24.988